services:
  xxx-web:
    container_name: xxx-web
    ports:
      - 61001:80
    volumes:
      - ~/Desktop/docker/universe/xxx-web/dist/:/usr/share/nginx/html/
      - ~/Desktop/docker/universe/xxx-web/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx
